In [2]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense

# Function to split a univariate sequence into samples
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequence)):
        # Find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        # Check if we are beyond the sequence
        if out_end_ix > len(sequence):
            break
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# Define a new dataset
raw_seq = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100]
# Choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# Split into samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)

# Display the input-output pairs
print("\nInput-Output Pairs:")
print("| Input (X)          | Output (y)   |")
print("|--------------------|--------------|")
for i in range(len(X)):
    print(f"| {X[i]} | {y[i]} |")

# Define the model
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_steps_in))
model.add(Dense(n_steps_out))
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X, y, epochs=2000, verbose=0)

# Demonstrate prediction with new input
x_input = array([900, 1000, 1100])  # Example input
x_input = x_input.reshape((1, n_steps_in))
yhat = model.predict(x_input, verbose=0)

# Display the prediction
print("\nPrediction:")
print(f"Given input sequence {x_input.flatten().tolist()}, the predicted values are: {yhat[0].tolist()}")


Input-Output Pairs:
| Input (X)          | Output (y)   |
|--------------------|--------------|
| [100 200 300] | [400 500] |
| [200 300 400] | [500 600] |
| [300 400 500] | [600 700] |
| [400 500 600] | [700 800] |
| [500 600 700] | [800 900] |
| [600 700 800] | [ 900 1000] |
| [700 800 900] | [1000 1100] |

Prediction:
Given input sequence [900, 1000, 1100], the predicted values are: [1198.833251953125, 1300.57763671875]
