In [3]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense

# Function to split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if end_ix > len(sequence) - 1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# Define a new dataset
raw_seq = [5, 15, 25, 35, 45, 55, 65, 75, 85, 95, 105]

# Define the number of time steps
n_steps = 3

# Split the sequence into samples
X, y = split_sequence(raw_seq, n_steps)

# Display the input-output pairs
print("\nInput-Output Pairs:")
print("| Input (X)  | Output (y) |")
print("|------------|------------|")
for i in range(len(X)):
    print(f"| {X[i]} | {y[i]:>10} |")

# Define the model
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_steps))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Train the model
history = model.fit(X, y, epochs=2000, verbose=0)

# Make predictions on new data
x_input = array([85, 95, 105])  # A sample sequence for prediction
x_input = x_input.reshape((1, n_steps))
yhat = model.predict(x_input, verbose=0)

# Extract the final training loss
final_loss = history.history['loss'][-1]

# Display the prediction and loss
print("\nPrediction:")
print(f"Given input sequence {x_input.flatten()}, the predicted next value is {yhat[0][0]:.2f}")
print(f"Final training loss: {final_loss:.6f}")


Input-Output Pairs:
| Input (X)  | Output (y) |
|------------|------------|
| [ 5 15 25] |         35 |
| [15 25 35] |         45 |
| [25 35 45] |         55 |
| [35 45 55] |         65 |
| [45 55 65] |         75 |
| [55 65 75] |         85 |
| [65 75 85] |         95 |
| [75 85 95] |        105 |

Prediction:
Given input sequence [ 85  95 105], the predicted next value is 116.41
Final training loss: 0.001249
